version: '1.0'

services:
  # setup:
  #   build:
  #     context: setup/
  #     args:
  #       ELASTIC_VERSION: ${ELASTIC_VERSION}
  #   init: true
  #   volumes:
  #     - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
  #     - ./setup/helpers.sh:/helpers.sh:ro,Z
  #     - ./setup/roles:/roles:ro,Z
  #     - setup:/state:Z
  #   environment:
  #     ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
  #     LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
  #     KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
  #     METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
  #     FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
  #     HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
  #     MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
  #     BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
  #   networks:
  #     - elk
  #   depends_on:
  #     - es01

  es01:
    build:
      context: es01/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./es01/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./es01:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: es01
      cluster.name: es
      cluster.initial_master_nodes: es01,es02,es03
      discovery.seed_hosts: es02,es03
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      bootstrap.memory_lock: true
      xpack.security.enabled: false
    networks:
      - elk
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    ulimits:
      memlock:
        soft: -1
        hard: -1

  es02:
    build:
      context: es02/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./es02/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./es02:/usr/share/elasticsearch/data:Z
    ports:
      - 9201:9200
      - 9301:9300
    environment:
      node.name: es02
      cluster.name: es
      cluster.initial_master_nodes: es01,es02,es03
      discovery.seed_hosts: es01,es03
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      bootstrap.memory_lock: true
      xpack.security.enabled: false
    networks:
      - elk
    depends_on:
      - es01
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    ulimits:
      memlock:
        soft: -1
        hard: -1
      
  es03:
    build:
      context: es03/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./es03/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./es03:/usr/share/elasticsearch/data:Z
    ports:
      - 9202:9200
      - 9302:9300
    environment:
      node.name: es03
      cluster.name: es
      cluster.initial_master_nodes: es01,es02,es03
      discovery.seed_hosts: es01,es02
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      bootstrap.memory_lock: true
      xpack.security.enabled: false
    networks:
      - elk
    depends_on:
      - es02
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s http://localhost:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
    ulimits:
      memlock:
        soft: -1
        hard: -1

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./logstash/config:/usr/share/logstash/config:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
      - ./logstash/data:/usr/share/logstash/dataFiles:ro,Z
      - ./logstash/dataDump:/usr/share/logstash/dataDump
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms1g -Xmx1g
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      monitoring.elasticsearch.hosts: http://es01:9200
    networks:
      - elk
    depends_on:
      es01:
        condition: service_healthy
    

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elk
    depends_on:
      es01:
        condition: service_healthy
      

networks:
  elk:
    driver: bridge

volumes:
  setup:
  elasticsearch:
